##● Ejercicios:
(1) Dado un corpus de documentos representados por una lista de textos, devolver una matriz con la representación one-hot-encoding.

(2) Dado un corpus de documentos representados por una lista de textos, devolver una matriz con la representación vectores de frecuencia.

(3) Dado un corpus de documentos representados por una lista de textos, devolver una matriz con la representación TFIDF.

(4) Escribir una función que reciba la matriz representando el corpus y el índice de un documento y devuelva los documentos ordenados por similitud coseno.

(5) Implementar (3) con matrices sparse de la librería SciPy.

In [1]:
  import numpy as np
  import pandas as pd

In [30]:
# creamos un dataframe para los documentos 

doc = pd.DataFrame({'texto':['hola como estas a que hora llegas','que tal te va como estas como viniste',
                                                               'buenos dias donde estas','de donde sos nunca te vi por aca',
                                                               'hola estoy afuera de tu casa donde estas','estoy a dos cuadras llegando',
                                                               'ey como te fue en tu nuevo trabajo','no estoy en mi casa te llamo luego',
                                                               'te busco por el aeropuerto','hola hola hola cuando llegas']})

In [31]:
doc

texto
0         hola como estas a que hora llegas
1     que tal te va como estas como viniste
2                   buenos dias donde estas
3          de donde sos nunca te vi por aca
4  hola estoy afuera de tu casa donde estas
5              estoy a dos cuadras llegando
6        ey como te fue en tu nuevo trabajo
7        no estoy en mi casa te llamo luego
8                te busco por el aeropuerto
9              hola hola hola cuando llegas

In [32]:
# ONE HOT ENCODING
corpus  = doc['texto']
corpus

0           hola como estas a que hora llegas
1       que tal te va como estas como viniste
2                     buenos dias donde estas
3            de donde sos nunca te vi por aca
4    hola estoy afuera de tu casa donde estas
5                estoy a dos cuadras llegando
6          ey como te fue en tu nuevo trabajo
7          no estoy en mi casa te llamo luego
8                  te busco por el aeropuerto
9                hola hola hola cuando llegas
Name: texto, dtype: object

Representacion en **One Hot Encoding**

In [33]:
corpus_f = []
for frase in corpus:
  corpus_f+=(frase.split())
  #for palabra in frase:
   # corpus_f.append(palabra)
corpus_uniq = np.array(corpus_f).flatten()

In [34]:
pal,count = np.unique(corpus_uniq,return_counts=True)
corpus_dict_frec = dict(zip(pal,count))
corpus_pos =dict(zip(pal,np.arange(pal.shape[0])))

In [35]:
corpus_dict_frec

{'a': 2,
 'aca': 1,
 'aeropuerto': 1,
 'afuera': 1,
 'buenos': 1,
 'busco': 1,
 'casa': 2,
 'como': 4,
 'cuadras': 1,
 'cuando': 1,
 'de': 2,
 'dias': 1,
 'donde': 3,
 'dos': 1,
 'el': 1,
 'en': 2,
 'estas': 4,
 'estoy': 3,
 'ey': 1,
 'fue': 1,
 'hola': 5,
 'hora': 1,
 'llamo': 1,
 'llegando': 1,
 'llegas': 2,
 'luego': 1,
 'mi': 1,
 'no': 1,
 'nuevo': 1,
 'nunca': 1,
 'por': 2,
 'que': 2,
 'sos': 1,
 'tal': 1,
 'te': 5,
 'trabajo': 1,
 'tu': 2,
 'va': 1,
 'vi': 1,
 'viniste': 1}

In [36]:
OneHotE = np.zeros((corpus.shape[0],pal.shape[0]))
OneHotE.shape

(10, 40)

In [37]:
i = 0
for doc in corpus:
  for palabra in doc.split(" "):
    # obtengo el indice donde esta almacenada la palabra en el corpus
    index = corpus_pos.get(palabra)
    OneHotE[i,index]=1
  i+=1

In [38]:
# Verificamos que el algoritmo de One Hot Encoding es correcto
# el doc en posicion 0 es:
corpus[0]

'hola como estas a que hora llegas'

In [39]:
# El corpus de palabras de todos los docs es el siguiente
pal

array(['a', 'aca', 'aeropuerto', 'afuera', 'buenos', 'busco', 'casa',
       'como', 'cuadras', 'cuando', 'de', 'dias', 'donde', 'dos', 'el',
       'en', 'estas', 'estoy', 'ey', 'fue', 'hola', 'hora', 'llamo',
       'llegando', 'llegas', 'luego', 'mi', 'no', 'nuevo', 'nunca', 'por',
       'que', 'sos', 'tal', 'te', 'trabajo', 'tu', 'va', 'vi', 'viniste'],
      dtype='<U10')

In [40]:
# El one hot encoding del primer documento es
OneHotE[0,:]

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [41]:
# Verificamos las palabras contenidas
pal[ OneHotE[0,:].astype(int)==1 ]

array(['a', 'como', 'estas', 'hola', 'hora', 'llegas', 'que'],
      dtype='<U10')

Representacion en **vectores de frecuencia** 

In [42]:
VectorFrec = np.zeros((corpus.shape[0],pal.shape[0]))
VectorFrec.shape

(10, 40)

In [43]:
i = 0
for doc in corpus:
  for palabra in doc.split(" "):
    # obtengo el indice donde esta almacenada la palabra en el corpus
    index = corpus_pos.get(palabra)
    VectorFrec[i,index]+=1
  i+=1

In [44]:
VectorFrec

array([[1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 1., 1., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
        1., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
        1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
   

In [45]:
# verificamos con algun doc que contenga repetida una palabra
corpus[1]

'que tal te va como estas como viniste'

In [46]:
# la palabra "como" (index 7) aparece dos vecees
VectorFrec[1]

array([0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 1.])

In [47]:
# el corpus 
corpus_pos

{'a': 0,
 'aca': 1,
 'aeropuerto': 2,
 'afuera': 3,
 'buenos': 4,
 'busco': 5,
 'casa': 6,
 'como': 7,
 'cuadras': 8,
 'cuando': 9,
 'de': 10,
 'dias': 11,
 'donde': 12,
 'dos': 13,
 'el': 14,
 'en': 15,
 'estas': 16,
 'estoy': 17,
 'ey': 18,
 'fue': 19,
 'hola': 20,
 'hora': 21,
 'llamo': 22,
 'llegando': 23,
 'llegas': 24,
 'luego': 25,
 'mi': 26,
 'no': 27,
 'nuevo': 28,
 'nunca': 29,
 'por': 30,
 'que': 31,
 'sos': 32,
 'tal': 33,
 'te': 34,
 'trabajo': 35,
 'tu': 36,
 'va': 37,
 'vi': 38,
 'viniste': 39}

Representacion en **TF-IDF**

In [48]:
# Calculamos el vector de frecuencia inversa del corpus (IDF) con 
# IDF = log(total_doc_corpus/cant_doc_donde_aparece_C/palabra)
total_doc_corpus = corpus.shape[0]

In [49]:
# Inicializo con ceros para luego contar la cantidad de documentos en que esta cada palabra
cant_doc_palabra = np.zeros(pal.shape[0])

In [50]:
# recorro las palabras unicas en el corpus y me fijo si esta en cada doc
for i in range(pal.shape[0]):
  for j in range(corpus.shape[0]):
    if pal[i] in corpus[j].split():
      cant_doc_palabra[i] += 1      

In [51]:
cant_doc_palabra

array([2., 1., 1., 1., 1., 1., 2., 3., 1., 1., 2., 1., 3., 1., 1., 2., 4.,
       3., 1., 1., 3., 1., 1., 1., 2., 1., 1., 1., 1., 1., 2., 2., 1., 1.,
       5., 1., 2., 1., 1., 1.])

In [52]:
#Cantidad de documentos que contienen la palabra 
dict_doc_pal = dict(zip(pal,cant_doc_palabra))
dict_doc_pal

{'a': 2.0,
 'aca': 1.0,
 'aeropuerto': 1.0,
 'afuera': 1.0,
 'buenos': 1.0,
 'busco': 1.0,
 'casa': 2.0,
 'como': 3.0,
 'cuadras': 1.0,
 'cuando': 1.0,
 'de': 2.0,
 'dias': 1.0,
 'donde': 3.0,
 'dos': 1.0,
 'el': 1.0,
 'en': 2.0,
 'estas': 4.0,
 'estoy': 3.0,
 'ey': 1.0,
 'fue': 1.0,
 'hola': 3.0,
 'hora': 1.0,
 'llamo': 1.0,
 'llegando': 1.0,
 'llegas': 2.0,
 'luego': 1.0,
 'mi': 1.0,
 'no': 1.0,
 'nuevo': 1.0,
 'nunca': 1.0,
 'por': 2.0,
 'que': 2.0,
 'sos': 1.0,
 'tal': 1.0,
 'te': 5.0,
 'trabajo': 1.0,
 'tu': 2.0,
 'va': 1.0,
 'vi': 1.0,
 'viniste': 1.0}

In [53]:
# creamos el vector IDF
IDF = np.log(total_doc_corpus/cant_doc_palabra)
IDF
# vemos que la frecuencia inversa de la palabra que aparece en mas documentos es mas chica

array([1.60943791, 2.30258509, 2.30258509, 2.30258509, 2.30258509,
       2.30258509, 1.60943791, 1.2039728 , 2.30258509, 2.30258509,
       1.60943791, 2.30258509, 1.2039728 , 2.30258509, 2.30258509,
       1.60943791, 0.91629073, 1.2039728 , 2.30258509, 2.30258509,
       1.2039728 , 2.30258509, 2.30258509, 2.30258509, 1.60943791,
       2.30258509, 2.30258509, 2.30258509, 2.30258509, 2.30258509,
       1.60943791, 1.60943791, 2.30258509, 2.30258509, 0.69314718,
       2.30258509, 1.60943791, 2.30258509, 2.30258509, 2.30258509])

In [55]:
# calculamos la matriz TF (cantidad de veces que una palabra aparece en cada documento por cada doc) 
TF = np.zeros((corpus.shape[0],pal.shape[0]))
for j in range(corpus.shape[0]):
  a,c = np.unique(corpus[j].split(),return_counts=True)
  tfj = dict(zip(a,c))
  print(tfj)
  for i in range(pal.shape[0]):    
    if pal[i] in corpus[j].split():
      TF[j,i] = tfj.get(pal[i])  




{'a': 1, 'como': 1, 'estas': 1, 'hola': 1, 'hora': 1, 'llegas': 1, 'que': 1}
{'como': 2, 'estas': 1, 'que': 1, 'tal': 1, 'te': 1, 'va': 1, 'viniste': 1}
{'buenos': 1, 'dias': 1, 'donde': 1, 'estas': 1}
{'aca': 1, 'de': 1, 'donde': 1, 'nunca': 1, 'por': 1, 'sos': 1, 'te': 1, 'vi': 1}
{'afuera': 1, 'casa': 1, 'de': 1, 'donde': 1, 'estas': 1, 'estoy': 1, 'hola': 1, 'tu': 1}
{'a': 1, 'cuadras': 1, 'dos': 1, 'estoy': 1, 'llegando': 1}
{'como': 1, 'en': 1, 'ey': 1, 'fue': 1, 'nuevo': 1, 'te': 1, 'trabajo': 1, 'tu': 1}
{'casa': 1, 'en': 1, 'estoy': 1, 'llamo': 1, 'luego': 1, 'mi': 1, 'no': 1, 'te': 1}
{'aeropuerto': 1, 'busco': 1, 'el': 1, 'por': 1, 'te': 1}
{'cuando': 1, 'hola': 3, 'llegas': 1}


In [56]:
TF

array([[1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 1., 1., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
        1., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
        1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
   

In [57]:
TF.shape

(10, 40)

In [58]:
IDF.shape

(40,)

In [59]:
TF_IDF = TF * IDF
TF_IDF.shape

(10, 40)

In [60]:
TF_IDF

array([[1.60943791, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.2039728 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.91629073, 0.        , 0.        , 0.        ,
        1.2039728 , 2.30258509, 0.        , 0.        , 1.60943791,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.60943791, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 2.40794561, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.91629073, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.60943791, 0.        , 2.3

Similitud **Coseno**

In [109]:
# 1 -> Cuando los textos son parecidos
#0  -> Cuando los textos son diferentes
def Compute_Cosine_Sim(tfidf,doc):
  Cos_sim = list()
  for i in range(tfidf.shape[0]):
    Cos_sim.append(np.inner(tfidf[i,:],tfidf[doc,:])/(np.linalg.norm(tfidf[i,:]) * np.linalg.norm(tfidf[doc,:])))
  
  index = np.arange(tfidf.shape[0])
  Data = pd.DataFrame({'Doc':index.T,'Cosine Sim':cos_sim})
  Data.set_index('Doc', inplace=True)
  Data = Data.sort_values('Cosine Sim',ascending=False)
  return Data


Los documentos mas similares son:

In [110]:
Compute_Cosine_Sim(TF_IDF,1)

Cosine Sim
Doc            
1      1.000000
0      0.304993
6      0.125483
2      0.046201
4      0.038821
8      0.021792
3      0.017839
7      0.017839
5      0.000000
9      0.000000

Utilizando matrices sparce para TF_IDF

In [121]:
from scipy.sparse import csr_matrix 
mask = TF_IDF != 0
row,col = np.where(mask)
data = TF_IDF[mask]


In [124]:
row,col

(array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3,
        3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6,
        6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9]),
 array([ 0,  7, 16, 20, 21, 24, 31,  7, 16, 31, 33, 34, 37, 39,  4, 11, 12,
        16,  1, 10, 12, 29, 30, 32, 34, 38,  3,  6, 10, 12, 16, 17, 20, 36,
         0,  8, 13, 17, 23,  7, 15, 18, 19, 28, 34, 35, 36,  6, 15, 17, 22,
        25, 26, 27, 34,  2,  5, 14, 30, 34,  9, 20, 24]))

In [122]:
data

array([1.60943791, 1.2039728 , 0.91629073, 1.2039728 , 2.30258509,
       1.60943791, 1.60943791, 2.40794561, 0.91629073, 1.60943791,
       2.30258509, 0.69314718, 2.30258509, 2.30258509, 2.30258509,
       2.30258509, 1.2039728 , 0.91629073, 2.30258509, 1.60943791,
       1.2039728 , 2.30258509, 1.60943791, 2.30258509, 0.69314718,
       2.30258509, 2.30258509, 1.60943791, 1.60943791, 1.2039728 ,
       0.91629073, 1.2039728 , 1.2039728 , 1.60943791, 1.60943791,
       2.30258509, 2.30258509, 1.2039728 , 2.30258509, 1.2039728 ,
       1.60943791, 2.30258509, 2.30258509, 2.30258509, 0.69314718,
       2.30258509, 1.60943791, 1.60943791, 1.60943791, 1.2039728 ,
       2.30258509, 2.30258509, 2.30258509, 2.30258509, 0.69314718,
       2.30258509, 2.30258509, 2.30258509, 1.60943791, 0.69314718,
       2.30258509, 3.61191841, 1.60943791])

In [123]:
# Recuperamos la matriz original 
csr_matrix( (data,(row,col)) , shape =TF_IDF.shape ).toarray()

array([[1.60943791, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.2039728 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.91629073, 0.        , 0.        , 0.        ,
        1.2039728 , 2.30258509, 0.        , 0.        , 1.60943791,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.60943791, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 2.40794561, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.91629073, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.60943791, 0.        , 2.3